apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-nilspet-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dpl-nilspet-redis
  template:
    metadata:
      labels:
        app: dpl-nilspet-redis
    spec:
      containers:
        - name: nilspet-redis
          image: nilspet-redis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379