apiVersion: v1
kind: Service
metadata:
  name: svc-nilspet-facade
spec:
  type: NodePort
  selector:
    app: dpl-nilspet-facade
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30005