apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: nilspet-facade
          image: nilspet-facade:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
        - name: nilspet-postgresql
          image: nilspet-postgresql:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432